version: "3"
services:
  app:
    container_name: app
    restart: always
    build: ./node
    ports:
      - "3000:3000"
    volumes:
      - "./node:/usr/src/app"
    working_dir:
      /usr/src/app
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongo
    ports:
    - "27017:27017"