version: "3"
services:
  app:
    container_name: app
    restart: always
    build: ./node
    ports:
      - "3000:3000"
    # depends_on:
    #   - redis
    # env_file:
    #   node.env
    volumes:
      - "./node:/usr/src/app"
    working_dir:
      /usr/src/app